[package]
name = "layout"
version = "0.1.0"
edition = "2021"

[features]
default = ["color", "layout"]
color = ["oklab", "rgb", "ufmt"]
layout = ["allsorts", "log", "rtext", "thiserror"]

[dependencies]
rtext = { git = "https://martinkolariknp@bitbucket.org/martinkolariknp/rtext.git", optional = true }

oklab = { version = "^1.0", optional = true }
rgb = { version = "^0.8", default-features = false, features = [
    "argb",
], optional = true }

allsorts = { version = "^0.11", optional = true }
log = { version = "^0.4", default-features = false, optional = true }
thiserror = { version = "^1.0", optional = true }
ufmt = { version = "^0.1", features = [
    "std",
], default-features = false, optional = true }
